'use strict';

/*
 * The 114 surahs: number, name, English meaning, and ayah count.
 *
 * Generated from api.alquran.cloud rather than typed, and bundled rather than
 * fetched at runtime, so the verse picker works offline and no name or count
 * here is something someone transcribed from memory.
 *
 * The ayah count is what bounds the picker — it is the only thing standing
 * between a user and asking for a verse that does not exist.
 */

/** @type {Array<[number, string, string, number]>} number, name, meaning, ayahs */
const SURAHS = [
  [1, "Al-Faatiha", "The Opening", 7],
  [2, "Al-Baqara", "The Cow", 286],
  [3, "Aal-i-Imraan", "The Family of Imraan", 200],
  [4, "An-Nisaa", "The Women", 176],
  [5, "Al-Maaida", "The Table", 120],
  [6, "Al-An'aam", "The Cattle", 165],
  [7, "Al-A'raaf", "The Heights", 206],
  [8, "Al-Anfaal", "The Spoils of War", 75],
  [9, "At-Tawba", "The Repentance", 129],
  [10, "Yunus", "Jonas", 109],
  [11, "Hud", "Hud", 123],
  [12, "Yusuf", "Joseph", 111],
  [13, "Ar-Ra'd", "The Thunder", 43],
  [14, "Ibrahim", "Abraham", 52],
  [15, "Al-Hijr", "The Rock", 99],
  [16, "An-Nahl", "The Bee", 128],
  [17, "Al-Israa", "The Night Journey", 111],
  [18, "Al-Kahf", "The Cave", 110],
  [19, "Maryam", "Mary", 98],
  [20, "Taa-Haa", "Taa-Haa", 135],
  [21, "Al-Anbiyaa", "The Prophets", 112],
  [22, "Al-Hajj", "The Pilgrimage", 78],
  [23, "Al-Muminoon", "The Believers", 118],
  [24, "An-Noor", "The Light", 64],
  [25, "Al-Furqaan", "The Criterion", 77],
  [26, "Ash-Shu'araa", "The Poets", 227],
  [27, "An-Naml", "The Ant", 93],
  [28, "Al-Qasas", "The Stories", 88],
  [29, "Al-Ankaboot", "The Spider", 69],
  [30, "Ar-Room", "The Romans", 60],
  [31, "Luqman", "Luqman", 34],
  [32, "As-Sajda", "The Prostration", 30],
  [33, "Al-Ahzaab", "The Clans", 73],
  [34, "Saba", "Sheba", 54],
  [35, "Faatir", "The Originator", 45],
  [36, "Yaseen", "Yaseen", 83],
  [37, "As-Saaffaat", "Those drawn up in Ranks", 182],
  [38, "Saad", "The letter Saad", 88],
  [39, "Az-Zumar", "The Groups", 75],
  [40, "Ghafir", "The Forgiver", 85],
  [41, "Fussilat", "Explained in detail", 54],
  [42, "Ash-Shura", "Consultation", 53],
  [43, "Az-Zukhruf", "Ornaments of gold", 89],
  [44, "Ad-Dukhaan", "The Smoke", 59],
  [45, "Al-Jaathiya", "Crouching", 37],
  [46, "Al-Ahqaf", "The Dunes", 35],
  [47, "Muhammad", "Muhammad", 38],
  [48, "Al-Fath", "The Victory", 29],
  [49, "Al-Hujuraat", "The Inner Apartments", 18],
  [50, "Qaaf", "The letter Qaaf", 45],
  [51, "Adh-Dhaariyat", "The Winnowing Winds", 60],
  [52, "At-Tur", "The Mount", 49],
  [53, "An-Najm", "The Star", 62],
  [54, "Al-Qamar", "The Moon", 55],
  [55, "Ar-Rahmaan", "The Beneficent", 78],
  [56, "Al-Waaqia", "The Inevitable", 96],
  [57, "Al-Hadid", "The Iron", 29],
  [58, "Al-Mujaadila", "The Pleading Woman", 22],
  [59, "Al-Hashr", "The Exile", 24],
  [60, "Al-Mumtahana", "She that is to be examined", 13],
  [61, "As-Saff", "The Ranks", 14],
  [62, "Al-Jumu'a", "Friday", 11],
  [63, "Al-Munaafiqoon", "The Hypocrites", 11],
  [64, "At-Taghaabun", "Mutual Disillusion", 18],
  [65, "At-Talaaq", "Divorce", 12],
  [66, "At-Tahrim", "The Prohibition", 12],
  [67, "Al-Mulk", "The Sovereignty", 30],
  [68, "Al-Qalam", "The Pen", 52],
  [69, "Al-Haaqqa", "The Reality", 52],
  [70, "Al-Ma'aarij", "The Ascending Stairways", 44],
  [71, "Nooh", "Noah", 28],
  [72, "Al-Jinn", "The Jinn", 28],
  [73, "Al-Muzzammil", "The Enshrouded One", 20],
  [74, "Al-Muddaththir", "The Cloaked One", 56],
  [75, "Al-Qiyaama", "The Resurrection", 40],
  [76, "Al-Insaan", "Man", 31],
  [77, "Al-Mursalaat", "The Emissaries", 50],
  [78, "An-Naba", "The Announcement", 40],
  [79, "An-Naazi'aat", "Those who drag forth", 46],
  [80, "Abasa", "He frowned", 42],
  [81, "At-Takwir", "The Overthrowing", 29],
  [82, "Al-Infitaar", "The Cleaving", 19],
  [83, "Al-Mutaffifin", "Defrauding", 36],
  [84, "Al-Inshiqaaq", "The Splitting Open", 25],
  [85, "Al-Burooj", "The Constellations", 22],
  [86, "At-Taariq", "The Morning Star", 17],
  [87, "Al-A'laa", "The Most High", 19],
  [88, "Al-Ghaashiya", "The Overwhelming", 26],
  [89, "Al-Fajr", "The Dawn", 30],
  [90, "Al-Balad", "The City", 20],
  [91, "Ash-Shams", "The Sun", 15],
  [92, "Al-Lail", "The Night", 21],
  [93, "Ad-Dhuhaa", "The Morning Hours", 11],
  [94, "Ash-Sharh", "The Consolation", 8],
  [95, "At-Tin", "The Fig", 8],
  [96, "Al-Alaq", "The Clot", 19],
  [97, "Al-Qadr", "The Power, Fate", 5],
  [98, "Al-Bayyina", "The Evidence", 8],
  [99, "Az-Zalzala", "The Earthquake", 8],
  [100, "Al-Aadiyaat", "The Chargers", 11],
  [101, "Al-Qaari'a", "The Calamity", 11],
  [102, "At-Takaathur", "Competition", 8],
  [103, "Al-Asr", "The Declining Day, Epoch", 3],
  [104, "Al-Humaza", "The Traducer", 9],
  [105, "Al-Fil", "The Elephant", 5],
  [106, "Quraish", "Quraysh", 4],
  [107, "Al-Maa'un", "Almsgiving", 7],
  [108, "Al-Kawthar", "Abundance", 3],
  [109, "Al-Kaafiroon", "The Disbelievers", 6],
  [110, "An-Nasr", "Divine Support", 3],
  [111, "Al-Masad", "The Palm Fibre", 5],
  [112, "Al-Ikhlaas", "Sincerity", 4],
  [113, "Al-Falaq", "The Dawn", 5],
  [114, "An-Naas", "Mankind", 6],
];

module.exports = { SURAHS };
